### PR TITLE
build_keyboard_adjacency_graphs.py: Support QWERTZ

### PR DESCRIPTION
**Pull request by ck-ws**
This change proposes adjacency graph support for (german) QWERTZ keyboards.

### CODE REVIEW

**Comment by stephtr** [comment]
I think `adjacency_graphs.coffee` should be generated before committing (because it is not included in package.json).

**Comment by stephtr** [comment]
The python script outputs non-ASCII as \u....
Wouldn't it be better to adjust `build_frequency_lists.py` to output utf8 characters?
I therefore made small adjustments to the build script ([stephtr/zxcvbn](https://github.com/stephtr/zxcvbn/commit/e39e35191b8a9ab15339264c336ddbacb9e6bbab)).

**Comment by ck-ws** [comment]
I have in mind that I tried that, but it failed executing. Would however be much more pretty 😉

**Comment by stephtr** [comment]
With python 2 I failed too (respectively didn't try hard enough), so I upgrade the script to python 3.

**Comment by stephtr** [comment]
Even though the qwertz graph gets build, it has to be referenced in `matching.coffee` and `scoring.coffee`.
Optimally one could also define a seperate `SHIFTED_RX` for qwertz layout and add some tests to `test-scoring`.

**Comment by lowe** [comment]
Quick update -- I have it on my roadmap to (a) support several common keyboard layouts (including QWERTZ) and (b) make it easier to add your own. I'm going to close this pull request for now and instead wait for the new system. Thanks for being patient.

**Comment by lowe** [comment]
ps. I opened a new issue for tracking purposes: https://github.com/dropbox/zxcvbn/issues/190

**Pull request closed without merging**
