### PR TITLE
Add support for detection of Password Haystacks. 

### PR DESCRIPTION
**Pull request by bmurray**
Detects repeating strings, instead of just individual repeating characters. 

https://www.grc.com/haystack.htm

Addresses #39 and #53

### CODE REVIEW

**Comment by azul** [comment]
@bmurray This is an improvement and it's great that it addresses repeated characters. But it does not really address the underlying problem of #53. Namely that repeated choices within a given searchspace still count fully. Let me give you an example for what i mean by that: 'dark, dark dark, dark'. (Note the missing comma in the middle). From reading your code it seems the base and the repeat have to be next to each other. So there is no haystack match within the string. I will give it a try. Maybe i misunderstand the code.

**Comment by bmurray** [comment]
You are right, it doesn't address that type of case. It addresses it in a simple way, and does catch the ". . . " case that #54 otherwise misses. Not a perfect solution, but works together with it. 

This pull is specifically addressing password haystacks, but has the side effect of addressing part of the problem in #53 .

**Comment by Pawtiko** [comment]
You might want to check out the work here: http://www.passwordmeter.com/
It seems to deal with repetition fairly well.

**Comment by lowe** [comment]
password haystack support coming soon -- i've been working on refactoring/packaging/build stuff these last few weeks, currently writing a full set of unit tests, and after that this is next on the queue.

**Comment by bmurray** [comment]
Awesome! Do you want me to update this patch, or are you writing up a new one?

**Comment by lowe** [comment]
No need, I'll write up a new one soon and refer to your diff.

**Comment by lowe** [comment]
I ended up going with a regex solution to find password haystacks. It covers all the corners I could think of, to give two examples: 

* recognizing aabaab as a repeat of 'aab', despite 'aa' also being a repeat
* recognizing abababab as a repeat of 'ab', despite 'abab' also being a repeat

feedback appreciated! new code lives in `repeat_match` in `src/matching.coffee`

**Pull request closed without merging**
