### PR TITLE
Add Dart language port

### PR DESCRIPTION
**Pull request by janheinrichmerker**

### CODE REVIEW

**Comment by yahya-uddin** [comment]
Now with flutter being as popular as it is, it would be great to feature a dart port.

**Comment by janheinrichmerker** [comment]
Sorry, forgot to sign the CLA, but now I have, so you can merge this PR now.

**Comment by janheinrichmerker** [comment]
@yahya-uddin The Dart port is still not referenced in the readme but I think it would be very handy for Dart/Flutter users.
Is there any chance this (minimal) PR can be merged?

**Comment by janheinrichmerker** [comment]
Closing due to inactivity

**Comment by yahya-uddin** [comment]
Why is this closed. It really should be merged!

**Comment by janheinrichmerker** [comment]
There was no response from the maintainers in over *5 years* 🤯, so I think it is highly unlikely this will ever be merged.
Although it is an extremely simple and easy-to-check contribution... :laughing:

**Comment by KerstinMaur** [comment]
I suppose two reasons might be that the [package is marked as deprecated](https://gitlab.com/exitlive/xcvbnm) and that users prefer [Nextcloud](https://nextcloud.com/) over [Dropbox](https://www.dropbox.com/). 🤔

**Pull request closed without merging**
