### PR TITLE
Add additional port.

### PR DESCRIPTION
**Pull request by wcjr**

### CODE REVIEW

**Comment by wcjr** [comment]
@lowe , Do I need to get a passing CI before you would consider this PR?  I'm assuming the CI is irrelevant since this was just an update to the README.  Thanks

**Comment by lowe** [comment]
Thanks! I fixed the continuous integration problem as well, sorry for the confusion.

**Comment by wcjr** [comment]
thanks @lowe , I appreciate you doing that.  I wasn't sure whether it was intentional or not but I noticed this PR wasn't merged 2 days ago when you were doing all that work.  Is there something I missed or was it just an oversight?  Looks like you were doing a bunch that day :-)

**Comment by lowe** [comment]
I'm not sure how I missed that, but I just added manually.

**Comment by wcjr** [comment]
Thanks, I'm sure it got lost in all those others you were doing :-)

**Pull request closed without merging**
